### ISSUE TITLE
Host website

### ISSUE THREAD

**Issue by omegabytes** [lanebreach/frontend#6]
Let's move away from hosting the site on Github. EC2 instance is fine for now, I'm open to suggestions. We will eventually get a CI/CD pipeline set up, so start building towards that and please document your build/deploy steps.

Steps:
- Configure clean EC2 env and save AMI
- deploy code on EC2 and snapshot
- Redirect www.lanebreach.org to new host

What needs to be done with Docker?

**Comment by omegabytes** [comment]
Our Github Pages solution will no longer be valid as of #17

**Comment by timshoaf** [comment]
Would you be amenable to utilizing K8S to host this application on AWS EKS? 

It seems like this may be one of the fastest methods to cloud agnosticism as well if you want to be able to hedge against cloud pricing changes from a budgetary standpoint since each provider has an alt (Azure has AKS, GCP has GKE).

I am happy to draw up the architecture proposal and work on the implementation as well.

**Comment by omegabytes** [comment]
Thanks for doing the heavy lifting on this @timshoaf! Love the refactor, already paying dividends.
